---
title: "JLS bibliometry in R"
output: html_notebook
---

## Preparations
```{r}
library(neo4r)
library(dplyr)
library(tidyr)
library(ggplot2)

con <- neo4j_api$new(
  url = "http://localhost:7474",
  user = "neo4j",
  password = "neo4j_local"
)

plot_query_result <- function(query, title, db="jls") {
  neo4j_result <- call_neo4j(paste("USE", db, query), con, type="row")

  # transform in a format that we can work with, clean up garbage years
  jco <- data.frame(t(neo4j_result)) |>
    rename(term=value, year=value.1, count=value.2) |>
    # filter by time span
    filter(year >= 1974 & year < 2023) #|>
  # only use those which have more than 5 citations in the time span
  #filter(count > 5)

  # add grouped data metrics
  jc <- jco %>%
    group_by(term) %>%
    mutate(jrnl_count=sum(count)) %>%
    arrange(desc(jrnl_count)) %>%
    ungroup() %>%
    group_by(year) %>%
    mutate(year_count=sum(count)) %>%
    ungroup() %>%
    group_by(term, year) %>%
    mutate(count=sum(count)) %>%
    ungroup() %>%
    # use only the first
    mutate(jrnl_rank_total = dense_rank(desc(jrnl_count))) %>%
    filter(jrnl_rank_total <30)

  # plot

  ggplot(jc, aes(x=term, y=year)) + coord_flip() +
    labs(title=title) +
    geom_point(aes(size=count, alpha=count/year_count)) +
    geom_line(aes(x= term, y = year, group=term),
              size=1.0, color="firebrick4", alpha=0.3 ) +
    scale_size(range=c(2,6))+ scale_alpha(range=c(0.3,1)) +
    scale_y_continuous(breaks = seq(min(jc$year),max(jc$year), by=2))+
    scale_x_discrete(limits=rev) +
    theme(legend.position = 'right'
          #,aspect.ratio = 1
      ,panel.background = element_rect(fill = '#FFFFFF')
      ,plot.title = element_text(size = 24)
      ,axis.title = element_text(size = 14, color = '#555555')
      ,axis.title.y = element_text(vjust = 1, angle = 90)#, face="bold")
      ,axis.title.x = element_text(hjust = .95)#,face="bold")
      ,axis.text.x = element_text(face="bold", angle = 90)
      ,axis.text.y = element_text(face="bold")
      ,axis.line.x = element_line(color="grey50", size=0.5)
      ,panel.grid.major.x = element_blank()
      ,panel.grid.major.y = element_line( size=.2, color="grey90" ))
}
```

## Citation of specific authors
```{r}
plot_query_result(
  title = "Citation of specific authors",
  query = '
    match (w1:Work)-[r:CITES]->(w2:Work)<-[:CREATOR_OF]-(a2:Author)
    where a2.family in ["dicey", "durkheim", "marx", "weber", "luhman", "habermas", "foucault", "bourdieu", "parsons"]
    RETURN a2.family, w2.year, count(*)
')

```

## Auto-generated list of 30 -most-cited authors

takes a while to complete, todo: cache it

```{r}
plot_query_result(
  title = "Most-cited authors",
  query = '
    match (w1:Work)-[r:CITES]->(w2:Work)<-[:CREATOR_OF]-(a2:Author)
    where a2.family <> "no_author"
    RETURN a2.display_name, w2.year, count(*)
')

```
