---
title: "R Notebook"
output: html_notebook
---

# Boulanger, Creutzfeldt, Hendry, JLS in Context

## Initialization:

```{r}
library(neo4r)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(data.table)
library(dotenv)
library(visNetwork)
library(igraph)
library(openxlsx)
library(timevis)
```

## Connect to Neo4J

```{r}
con <- neo4j_api$new(
  url = "http://localhost:7474",
  user = "neo4j",
  password = "neo4j_local"
)
# function to run queries which uses this connection
run_query <- function(query, db = 'jls') {
  neo4j_result <- call_neo4j(paste("use", db, query), con, type = "row")
  if ("error_code" %in% names(neo4j_result)) {
    print(neo4j_result$error_message)
    stop()
  }
  neo4j_result
}

```

## Define the plot function

```{r}
plot_timeline <- function(title, query, db = "jls",
                          min_count = 0, max_rank = 30,
                          year_start = 1974, year_end = 2025) {
  # execute cypher query
  neo4j_result <- run_query(query)

  # transform in a format that we can work with, clean up garbage years
  jco <- data.frame(t(neo4j_result)) |>
    rename(journal = value, year = value.1, count = value.2) |>
    filter(year >= year_start & year <= year_end) %>%
    filter(count >= min_count)

  # add grouped data metrics
  jc <- jco %>%
    group_by(journal) %>%
    mutate(jrnl_count = sum(count)) %>%
    arrange(desc(jrnl_count)) %>%
    ungroup() %>%
    group_by(year) %>%
    mutate(year_count = sum(count)) %>%
    ungroup() %>%
    group_by(journal, year) %>%
    mutate(count = sum(count)) %>%
    ungroup() %>%
    # limit the number of returned items
    mutate(jrnl_rank_total = dense_rank(desc(jrnl_count))) %>%
    filter(jrnl_rank_total <= max_rank)

  # Create a new column with the sum of count values per journal
  jc_sum <- jc %>%
    group_by(journal) %>%
    summarise(sum_count = sum(count)) %>%
    arrange(sum_count)

  # plot
  ggplot(jc, aes(x = journal, y = year)) +
    coord_flip() +
    labs(title = title) +
    geom_point(aes(size = count, alpha = count / year_count)) +
    geom_line(aes(x = journal, y = year, group = journal),
              size = 1.0, color = "firebrick4", alpha = 0.3) +
    #geom_bar(aes(x = journal, y = cumsum(count)), stat = "identity", alpha = 0.1, fill = "grey90", width = 0.8) +
    scale_size(range = c(2, 6)) +
    scale_alpha(range = c(0.3, 1)) +
    scale_y_continuous(breaks = seq(min(jc$year), max(jc$year), by = 2)) +
    scale_x_discrete(limits = jc_sum$journal) +
    theme(legend.position = 'right'
          #,aspect.ratio = 1
      , panel.background = element_rect(fill = '#FFFFFF')
      , plot.title = element_text(size = 24)
      , axis.title = element_text(size = 14, color = '#555555')
      , axis.title.y = element_text(vjust = 1, angle = 90) #, face="bold")
      , axis.title.x = element_text(hjust = .95) #,face="bold")
      , axis.text.x = element_text(face = "bold", angle = 90)
      , axis.text.y = element_text(face = "bold")
      , axis.line.x = element_line(color = "grey50", size = 0.5)
      , panel.grid.major.x = element_blank()
      , panel.grid.major.y = element_line(size = .2, color = "grey90"))
}
```

## Most-Cited Authors

```{r}
plot_timeline(
  "Most-cited authors",
  'match (v1:Venue)<-[:PUBLISHED_IN]-(w1:Work)-[:CITES]->(w2:Work)
    where v1.id = "j law soc" or v1.id="br j law soc"
    with w2
    match (a2:Author)-[:CREATOR_OF]->(w2)
    where a2.family <> "" and a2.family <> "no_author"
    RETURN a2.family as name, w2.year as year, count(*) as count')
```

## Citation of specific authors over time

### Socio-legal classics

```{r}
plot_timeline(
  "Socio-legal classics",
  'match (w1:Work)-[r:CITES]->(w2:Work)<-[:CREATOR_OF]-(a2:Author)
    where a2.family in ["foucault","weber","marx","bourdieu","luhmann","latour","arendt","benhabib","valverde","merry","silbey","teubner"]
    RETURN a2.family, w2.year, count(*)')
```

### Cownie-Bradley

```{r}
plot_timeline(
  "Most-cited authors",
  'match (v1:Venue)<-[:PUBLISHED_IN]-(w1:Work)-[:CITES]->(w2:Work)
    where v1.id = "j law soc" or v1.id="br j law soc" or
    with w1, w2
    match (a1:Author)-[:CREATOR_OF]->(w1), (a2:Author)-[:CREATOR_OF]->(w2)
    where a2.family = "cownie" or a2.family = "bradney" or
    RETURN a2.family as name, w2.year as year, count(*) as count')
```

## Cited journals 1974-2020

```{r}
plot_timeline(
  "Citation of journals over time",
  'match (v1:Venue)<-[:PUBLISHED_IN]-(w1:Work)-[:CITES]->(w2:Work)-[:PUBLISHED_IN]-(v2:Venue)
    where v1.id = "j law soc" or v1.id="br j law soc"
    return v2.name, w1.year, count(*) as count',
  min_count = 1
)
```

## Cited journals 1974-1984

```{r}
plot_timeline(
  "Citation of journals over time",
  'match (v1:Venue)<-[:PUBLISHED_IN]-(w1:Work)-[:CITES]->(w2:Work)-[:PUBLISHED_IN]-(v2:Venue)
    where v1.id = "j law soc" or v1.id="br j law soc" and w1.year <= 1984
    return v2.name, w1.year, count(*) as count')
```

## Author's origin countries

```{r}
plot_timeline(
  "Author's origin countries, over time",
  'MATCH (w:Work)-[:PUBLISHED_IN]->(v:Venue)
  WHERE (v.id = "j law soc" OR v.id = "br j law soc") and w.id starts with "10."
  WITH w, v, w.year AS year
  MATCH (a:Author)-[:CREATOR_OF]->(w)
  MATCH (a)-[:AFFILIATED_WITH]->(i:Institution)-[:LOCATED_IN]->(c:Country)
  where c.name <> "" and c.name <> "uk, usa"
  RETURN c.name, year, COUNT(DISTINCT w) AS count',
  min_count = 1
)

```

## Author's origin continents

```{r}
plot_timeline(
  "Author's origin continents, over time",
  'MATCH (w:Work)-[:PUBLISHED_IN]->(v:Venue)
  WHERE (v.id = "j law soc" OR v.id = "br j law soc") and w.id starts with "10."
  WITH w, v, w.year AS year
  MATCH (a:Author)-[:CREATOR_OF]->(w)
  MATCH (a)-[:AFFILIATED_WITH]->(i:Institution)-[:LOCATED_IN]->(c:Country)-[:PART_OF]->(cn:Continent)
  where c.name <> ""
  RETURN cn.name, year, COUNT(DISTINCT w) AS count',
  min_count = 2
)
```
